### ISSUE TITLE
Key attribute

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Keas#103]
Should this have the Key Attribute?
https://github.com/ucdavis/Keas/blob/master/Keas.Core/Domain/AssignmentBase.cs#L12

**Comment by jcubbage** [comment]
There are several missing [Key] in the models right now.  This plus:
Assignmentbase
EquipmentAttribute
History
Notification
Person
Space (though there is a note regarding this in it)
SystemPermissions
Workstation (missing ID entirely. EF creates if missing)
WorkstationAttribute

**Comment by jSylvestre** [comment]
Nothing is breaking in Prod, so I'm closing this.
