### ISSUE TITLE
Add Key

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Keas#119]
When a Key is added and assigned, the serialId is not being passed to this method:
https://github.com/ucdavis/Keas/blob/master/Keas.Mvc/Controllers/Api/KeysController.cs#L100

Part of the problem with doing this is related to a missing include fixed in this pr #118

**Comment by jcubbage** [comment]
Is this fixed by now?

**Comment by jSylvestre** [comment]
Seems to be working fine. Closing
