### ISSUE TITLE
Update Dashboard

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Keas#148]
For the "homepage" dashboard (i.e. https://keas.azurewebsites.net/caesdo), let's clean it up to remove testing pages.

Dashboard Should have:
Assets (if they can see their team assets)
My Stuff (ideally we can put a badge up if they have assets waiting to confirm)
Team Administration (if they are an admin)

Header Bar should have:
Assets (if they have access)
My Stuff
Reports (if they have access)
Admin (if they are admin)

**Comment by jSylvestre** [comment]
![image](https://user-images.githubusercontent.com/469010/46968141-51f4b280-d067-11e8-83ce-a6e96ac6de97.png)
