### ISSUE TITLE
Admin section improvements

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Keas#171]
Some sub-pages allow you to go back to the main list (like add new org code) but the others don't. 
Admin roles uses a back arrow icon for an adding action
Assign role to use button is messed up
Add new team tag button messed up (though on edit it looks nice)
Maybe get rid of reports since it is already on the header?

https://keas.azurewebsites.net/caesdo/TeamAdmin/AddMemberRole

**Comment by jcubbage** [comment]
@cydoval I think the "a btn-primary" and "a btn-danger" styles need to match "input btn-primary" and "input btn-danger" styles. Sometimes use inputs, but often just use links for the cancel parts of forms. Or let me know better classes to use for these?
