### ISSUE TITLE
Preload issue?

### ISSUE THREAD

**Issue by jcubbage** [ucdavis/Keas#197]
![image](https://user-images.githubusercontent.com/599659/47468607-02259200-d7b1-11e8-8468-3667a989e098.png)

**Comment by srkirkland** [comment]
@jcubbage I don't get this on dev but I do on Azure.  Rocket-loader is something cloudflare injects in front of the site on prod.  Our integrity hashes look correct to me, so I think cloudflare is messing with stuff.  There is an option we can do to have cloudflare not preload, and I think that's probably what we should do. 

Sound good?

**Comment by jcubbage** [comment]
Fine by me. I just happened to notice it and wasn't sure the issue...or if it was a problem. Is that something you'd fix?

**Comment by srkirkland** [comment]
yea i'll take care of it

**Comment by jSylvestre** [comment]
Seems to be fixed.
