### ISSUE TITLE
keys allow space for code

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Keas#277]
Go! is enabled and saves a blank space on create key:

![image](https://user-images.githubusercontent.com/469010/49035610-2686dc80-f16a-11e8-9fc6-27f6092ea3cc.png)

**Comment by jpknoll** [comment]
What are the requirements for a key's code? Max/Min/Allowed Chars?

**Comment by jpknoll** [comment]
Check #285

**Comment by jSylvestre** [comment]
@jpknoll This isn't fixed. In addition, you can create a key with a space for a name and code...

![image](https://user-images.githubusercontent.com/469010/49104712-809fa480-f233-11e8-9146-5bd714be4aa2.png)

**Comment by jSylvestre** [comment]
@jpknoll A space only in the code is fixed, but you can still do this for the name.

**Comment by jpknoll** [comment]
Should be resolved now.
