### ISSUE TITLE
Key Serial Assign space

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Keas#283]
If you enter a new key that doesn't exist to assign to a space, it just spins:

![image](https://user-images.githubusercontent.com/469010/49045512-154bc900-f186-11e8-9c02-01d5f401e1e0.png)

from here:

![image](https://user-images.githubusercontent.com/469010/49045528-24cb1200-f186-11e8-81aa-8d2af8495a7a.png)

**Comment by jpknoll** [comment]
I mean, we could just not allow creating a new key from that modal....

**Comment by jpknoll** [comment]
Check #285

**Comment by jpknoll** [comment]
Resolved in #304
