### ISSUE TITLE
Associate an existing association

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Keas#284]
This happens here on the associate space as well on the spaces if you try to associate a key that is already associated. It just spins when you hit go.

![image](https://user-images.githubusercontent.com/469010/49045975-7cb64880-f187-11e8-99ee-0cd44ad381ec.png)

**Comment by jpknoll** [comment]
Yeah, it currently throws a bad request from the server.

We should be filtering the search fields for existing relationships, or at least detect and present a warning.

**Comment by jpknoll** [comment]
Fixed in #301
