### ISSUE TITLE
Unused Field

### ISSUE THREAD

**Issue by jpknoll** [ucdavis/Keas#291]
Thoughts on removing Group?

https://github.com/ucdavis/Keas/blob/5959b5339ab8e863cd47345263bc681d1177cf10/Keas.Core/Domain/AssetBase.cs#L21

**Comment by srkirkland** [comment]
@jpknoll agree.  Don't remember what it was supposed to be for

**Comment by jcubbage** [comment]
I think it was going to be used for sub-grouping members (e.g. Cosmology group in Physics). The functionality has been largely replaced by Tags.
