### ISSUE TITLE
Select Boxes text cutoff

### ISSUE THREAD

**Issue by jpknoll** [ucdavis/Keas#300]
![image](https://user-images.githubusercontent.com/214330/49184219-a9976680-f313-11e8-8275-5f5a854949ed.png)

Offending Line from bootstrap:

`
.form-control {
	height: calc(2.25rem + 2px);
}
`

Consider picking a better multiplier.

**Comment by cydoval** [comment]
height: calc(3rem + 2px);

**Comment by cydoval** [comment]
closed in design 7 branch
