### ISSUE TITLE
Nicer homepage design

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Keas#332]
Team homepage is just a bunch of links right now.  Maybe it needs some big icon/image buttons, not sure but something to direct people to what to use and give descriptions of each option.

Most people will only see 1 to 2 links so it isn't too information dense.

https://peaks.ucdavis.edu/caesdo/home/index

**Comment by jcubbage** [comment]
Vast majority of people will only see "My Stuff". Handful per team will see Team Assets, and 1-2 per team will also see Administer Team.

**Comment by srkirkland** [comment]
looks good to me now
