### ISSUE TITLE
Fire person in multiple teams

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Keas#353]
Send out an email or something to other team admins that this has happened

**Comment by jcubbage** [comment]
Maybe this is some sort of notification sent out to all the DepartmentAdmins for each team???

**Comment by jcubbage** [comment]
Maybe just add ability to see what other teams a person is part of?

**Comment by jcubbage** [comment]
From the CAO/IT Lead meeting - 1/10/19

**Comment by jSylvestre** [comment]
@jcubbage What if we add a link in the person details page that looks up all the teams that person is in and lists the dept admins for those teams as a contact person?
