### ISSUE TITLE
API for pulling person info

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Keas#374]
Each team should have a read-only endpoint which allows querying of their "Person" collection.  Should return related info including

Names 
Email
Login 
Role / Title
Phone 

Additionally it would be nice if, either by default or through a parameter, they could request space information to also be included, returning each user's workstations (room/building/tags)

**Comment by jSylvestre** [comment]
As the person's email can be changed, maybe also include the user email if different?

**Comment by jcubbage** [comment]
Except that the API is intended for a team's consumption and publication. So, they would want to use the email they know this person as. I suppose we could include the person name & email as well as the user name and email and let the team decide what to do with it.
