### ISSUE TITLE
some action colors are wrong

### ISSUE THREAD

**Issue by laholstege** [ucdavis/Keas#381]
access on /people/details
![image](https://user-images.githubusercontent.com/27025973/51345517-15fb3000-1a50-11e9-8541-392ca9e18b76.png)
spaces on keys/details
![image](https://user-images.githubusercontent.com/27025973/51345536-23b0b580-1a50-11e9-8ffc-da8c03683c64.png)
equipment on spaces/details
![image](https://user-images.githubusercontent.com/27025973/51345668-6d010500-1a50-11e9-9a02-9ec9ff0bb495.png)

**Comment by cydoval** [comment]
fixed in design8

**Comment by cydoval** [comment]
@laholstege what page would i find the code for these anomalies

**Comment by cydoval** [comment]
closed for realsies in design 9
