### ISSUE TITLE
home page without team needs a row

### ISSUE THREAD

**Issue by cydoval** [ucdavis/Keas#408]
homepage without team
<img width="1792" alt="screen shot 2019-01-18 at 12 45 02 pm" src="https://user-images.githubusercontent.com/1899553/51411992-e6ffbf80-1b1e-11e9-8773-c0c994d66e58.png">

@laholstege where in the protect folder is this page?

**Comment by jSylvestre** [comment]
@cydoval Is this what you are looking for:
https://github.com/ucdavis/Keas/blob/master/Keas.Mvc/Views/Confirm/SelectTeam.cshtml

**Comment by cydoval** [comment]
yea I believe so

**Comment by cydoval** [comment]
closed in design 8
