### ISSUE TITLE
Admin roles should be separate from team roles

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Keas#441]
Currently every time we check for team permissions, like KeyMaster, we also check system permissions to see if the user is a system admin.  I would argue a system admin should not be able to see a team's expiring keys, for example. An admin should be able to emulate, create teams, and probably add themselves to someone else's team. But I think it would simplify so much if we stopped checking for admin permissions

**Comment by jcubbage** [comment]
Closed with PR ##448
