### ISSUE TITLE
tags on spaces details are messed up

### ISSUE THREAD

**Issue by laholstege** [ucdavis/Keas#467]
![image](https://user-images.githubusercontent.com/27025973/52095308-5d68dc80-2577-11e9-8216-e51f8fbb1717.png)

**Comment by jcubbage** [comment]
I think this is an artifact of our combining the tags for keys, equipment, and workstations so when you search tags, you get any of those threes tags as such. Is there a way to do a distinct on that in React? If not, I need to go back and revisit the query.

**Comment by jcubbage** [comment]
Ln 26 of SpaceDetailContainer.
