### ISSUE TITLE
deleted items

### ISSUE THREAD

**Issue by jcubbage** [ucdavis/Keas#499]
Way to look-up delete equipment.

**Comment by jcubbage** [comment]
Also, way to mark equipment status. So Active => Retired => Bargin Barn.

**Comment by jSylvestre** [comment]
@jcubbage  Key Value Pairs.
Done.

**Comment by jcubbage** [comment]
I agree....and finally got buy-in from management on status. But, still need way to look-up deleted equipment.

**Comment by jSylvestre** [comment]
@jcubbage I suppose you could create a report. When you delete equipment, it does generate a history as well, so you could include when this was done and by whom.

**Comment by jSylvestre** [comment]
The equipment report and feed can show deleted equipment. Closing
