### ISSUE TITLE
Can't add tag when editing Key.

### ISSUE THREAD

**Issue by jcubbage** [ucdavis/Keas#503]
![image](https://user-images.githubusercontent.com/599659/52891013-ec135700-313c-11e9-830c-c99690b6b3bb.png)

**Comment by laholstege** [comment]
@jcubbage I wasn't able to reproduce this. is it still happening for you?

**Comment by jcubbage** [comment]
Yup...but only on Plant Sciences???? I have the following roles there: "Departmental Admin, Equip Master, Key Master". On CAES-Test, I'm only KeyMaster, and my edits work fine.

**Comment by jcubbage** [comment]
@laholstege : This happens on one particular key. Works fine on all the other ones I've tested.

**Comment by laholstege** [comment]
@jcubbage any idea what's weird about that one key?

**Comment by jcubbage** [comment]
@laholstege Yeah - we had 2 keys with the same code active in DB. Happened before we put safeguards against that. So, update was made, expected back 1 row updated, got 2, and throw error. Deleted second key => fixed.
