### ISSUE TITLE
Automated on/off boarding emails for users

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Keas#533]
The idea is that managing people in PEAKS should notify a department's existing on/off boarding process, to avoid duplicate work.

Simple version: An admin setting with an optional "Person Notification Email".  If it exists, whenever a person is created or deleted from a team, we send an email to that email address with the person's info.  i.e., "John Smith was created in PEAKS team XYZ.  Details: ...".   Admins would put their service-now email most likely and it would kick off their individual on/off boarding processes.

Complex version: Same as above but we add a toggle so the person creator can determine if they want the onboarding email sent.

**Comment by jSylvestre** [comment]
So... to do this:
- [ ] Add a column to the team table to hold the email
- [ ] Add a page to edit the email value
- [ ] Create a new table to hold the notification. Possibly expand the Notification table
- [ ] Create a new email template
- [ ] Create a new email service
- [ ] Update and deploy email job
- [ ] Everywhere a person can be added, deleted, or activated, call a new service to write the pending notification. Note!!! None of the imports are doing this at the moment

**Comment by jcubbage** [comment]
Is this going to work at all???? People already need to have a Kerberos to be added to PEAKS. For transfers from one department to another, that's fine, but on-boarding a brand new employee can not begin in PEAKS. On the other end, I'm not sure deleting/marking inactive is the first thing someone wants to do, so probably not going to be were they kick off that process with SSO.

**Comment by jSylvestre** [comment]
I think this is all done. Just testing tonight to make sure I deployed the job.

**Comment by jSylvestre** [comment]
Looked in the DB. Is done
