### ISSUE TITLE
React not remembering show 100 rows

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Keas#552]
@emhenn Didn't like it, so complain to him :)

**Comment by jcubbage** [comment]
Confirmed - go to people (on large department). Change to 100 rows. Hit details. Hit back - only 20 rows.

**Comment by jSylvestre** [comment]
https://www.robinwieruch.de/local-storage-react/

**Comment by jSylvestre** [comment]
`ReactTable
                data={this.props.spaces}
                ...
                defaultPageSize={10}
                ...`

**Comment by jSylvestre** [comment]
`                defaultPageSize={localStorage.getItem('SpaceDefaultPageSize') || 20}
                onPageSizeChange={(pageSize) => {localStorage.setItem('SpaceDefaultPageSize', pageSize);}}`
