### ISSUE TITLE
Bulk Edit People

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Keas#577]
From a help ticket, not sure if we want to do this:

4. Is there a way to bulk edit people? For example, I might want to edit a whole bunch of people to have the same category (staff), tag (CRU), or end date. Is there any way to facilitate this without having to click into each person individually, click edit, change the fields individually, then click Go?

**Comment by jcubbage** [comment]
I'm not sure how they would identify who they want to edit. Maybe if you wanted to tag all the staff with the same tag. But after initial load, how are you going to decide who needs a particular update?

**Comment by jSylvestre** [comment]
Scott suggested a non-react page that would list people with a checkbox and then have a few fields they could update.
