### ISSUE TITLE
From Help Ticket

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Keas#588]
INC0763158
Two feature requests:
 
1) Allow people API to pull all People Data: supervisor, category, etc
2) Create another access role for editing people. Because admin assistants often need to update people's profiles (especially after importing 300 people with no contact information), we are reluctant to give them Departmental Admin access to do so.

**Comment by jcubbage** [comment]
2) Ooooohhh.....PeopleMaster seems like a really bad name!

**Comment by jSylvestre** [comment]
@jcubbage 1 shouldn't be a problem, Just add those fields to the model and populate them?

**Comment by jcubbage** [comment]
@jSylvestre  has 1) covered.
@jcubbage  will take 2)
