### ISSUE TITLE
Key column filter

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Keas#645]
What is the difference between "Show All" and "Any"?
![image](https://user-images.githubusercontent.com/469010/59705518-66b7b600-91b3-11e9-8da7-46f33d7d2eca.png)

**Comment by jcubbage** [comment]
Take a look at KeyTable.tsx, Line 104-120. I agree the wording may be strange and might need to be wordsmithed, but the 2 are different. "Show all" will show all keys, regardless of if it has any keyserials. "Any" will show keys that have keyserials, but will exclude keys that have zero keyserials. I set up a demo at https://peaks.ucdavis.edu/caes-test/keys. Switch between them and "No Key Serial" will toggle.

**Comment by jSylvestre** [comment]
@jcubbage Change Any to With Serials? Has Serials?

**Comment by jcubbage** [comment]
@jSylvestre My choice of those to would be "Has Serials". I could also get behind "Has any", since the column is already labeled "Serials". Check with @cydoval?
