### ISSUE TITLE
Entry fields and Escape key

### ISSUE THREAD

**Issue by jcubbage** [ucdavis/Keas#649]
User reports hitting escape key at any point in the new asset modal closes the modal unexpectedly. They are hitting the escape key out of habit for things like drop down menus when they don't want to enter a value. I suggested they try the tab/shift-tab key.

@laholstege I figure this would be a key press capture and display a confirm dialog for escape key press. Is there a way to do this one place and attach to all the new asset modals?

**Comment by jSylvestre** [comment]
That is sort of default behavior, not sure if that should be changed.

**Comment by cydoval** [comment]
I think closing the modal with escape key is something we want to keep, perhaps we should add a confirm close to the modal if any data has been entered (if possible).

this article https://simplyaccessible.com/article/closing-modals/ confirms that closing modals via escape is common and should be maintained

**Comment by jcubbage** [comment]
I agree. I didn't say get rid of the escape key function. Just add a confirm to it.

**Comment by jcubbage** [comment]
@NabilFurmoli opened new issue for same topic. Assigned both to PR #651
