### ISSUE TITLE
IS3 Classifications

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Keas#650]
So, we may have need for new required fields.
Perhaps have a flag that says IS3 Requirement that will show fields and or make them required?

Expand access to have more fields such as a URL to a password manager for cert details?

Think about adding a list serve email for some kinds of expiration? Maybe still assign it to a person, but have a generic email that we can send to as well.

* [x] Add Fields to DB
* [x] Add Fields to domain object
* [x] Add Fields to Form(s)
* [ ] ~Update any dapper queries~
* [x] Update CSV Import
* [x] Script to default data based on Type
* [x] Search Fields on equipment list? (Maybe have a ... and dialog for more search fields)
* [ ] Link on form to official page for what these values are?
* [x] Reports / Json Dumps

**Comment by srkirkland** [comment]
https://security.ucop.edu/policies/institutional-information-and-it-resource-classification.html

@jSylvestre @laholstege So the idea would be we add two new fields for Equipment: "Protection Level" and "Availability Level".  They would be dropdowns w/ the values specified in that doc.

For all equipment types, we can optionally select one of the values for each field.  For some types they will be required (anything computer-related, specifically anything that can store data).

In the form for create/edit we should put it before "notes" so it's a first-class citizen

**Comment by jSylvestre** [comment]
@srkirkland Have you thought about how you want to populate existing data if it is required? Or just have it required on the page?

**Comment by srkirkland** [comment]
@jSylvestre well it can't be required in the DB because not all types will have info for those fields.  So I was just thinking required on the page, and thus old equipment would just be lazily updated as people next edit them.

**Comment by jSylvestre** [comment]
* [ ] Add Fields to DB
* [ ] Add Fields to domain object
* [ ] Add Fields to Form(s)
* [ ] Update CSV Import
* [ ] Script to default data based on Type
* [ ] Search Fields on equipment list? (Maybe have a ... and dialog for more search fields)
* [ ] Link on form to official page for what these values are

**Comment by jSylvestre** [comment]
Added filter in PR #666
