### ISSUE TITLE
INC0826683 -- Other people import sources

### ISSUE THREAD

**Issue by jSylvestre** [ucdavis/Keas#659]
User:

I ran into an issue yesterday with the students that I needed to be added.
They are not in PPS and may never be in PPS depending on if they work for
us or not. Every fall I have between 40-70 new MS and PhD students that
need to be added to PEAKS to assign keys and key cards to. The only way I
was able to add them in bulk was to create a mock key and input them with
there kerberos in a CSV document to import. There has to be a better way to
do this for students and visiting scholars who may not ever be in PPS.

**Comment by jSylvestre** [comment]
Perhaps there is a PPS lookup for this?
Another source to bulk load from?
Worst case, create a cvs people import.

**Comment by jcubbage** [comment]
I've tried everything I can to get good student data, and it doesn't work well. IF the students are grad students AND they have either a TA or GSR position, they will be in PPS. But, there are a ton of students in departments that do not fit that. IAM does have student look-up by major, but that may grab many more students then you intend, especially with grad groups (grad students in "nutrition" can be housed in any of 5-6 departments). So, I think CSV import for people is our best bet. This user clearly is using that as a method to get them in by doing key CSV.
