### ISSUE TITLE
Setup IAM service and auto create claims on login

### ISSUE THREAD

**Issue by srkirkland** [ucdavis/Keas#7]

**Comment by jcubbage** [comment]
This is done, correct?

**Comment by srkirkland** [comment]
@jcubbage yup, though we'll want to switch to our KEAS account once IAM gives us a key for that

**Comment by jcubbage** [comment]
So...we have an account that Rob created specifically for this project and it has an IAM key. It's the secret I'm using on my machines.

**Comment by srkirkland** [comment]
@jcubbage ah, didn't know we had an IAM key for that -- could you put it in the box folder i invited you to for keas?

**Comment by jcubbage** [comment]
@srkirkland Uploaded. I renamed your key in case we want to leave it there/use it later. Feel free to delete if that's a better idea.
